apiVersion: v1
kind: Service
metadata:
  name: flaskproject-svc
  namespace: test
  labels:
    app: flask-projects
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
    - port: 80           # this can be change right here 
      targetPort: 5000   # it has match with program 